
import pygame
from src.Misc import Misc

GAME_NAME = "Ninja Descent"

# SCREEN
SCREEN_WIDTH = 900
SCREEN_HEIGHT = SCREEN_WIDTH
SCREEN_SIZE =  (SCREEN_WIDTH, SCREEN_HEIGHT)
SCREEN_CENTER = (SCREEN_WIDTH / 2, SCREEN_HEIGHT / 2)
SCREEN_MARGIN = 0.0025 * SCREEN_WIDTH

# DRUNKARDS WALK DISPLAY
GRID_ROWS = 100
GRID_COLS = GRID_ROWS
CELL_SPACING = 10
DEFAULT_START_POS = (int(GRID_COLS / 2), int(GRID_ROWS / 2))
CELL_WIDTH = Misc.calculate_cell_size(SCREEN_WIDTH, GRID_COLS, CELL_SPACING)
CELL_HEIGHT = Misc.calculate_cell_size(SCREEN_HEIGHT, GRID_ROWS, CELL_SPACING)
GRID_WIDTH = Misc.calculate_grid_size(CELL_WIDTH, CELL_SPACING,  GRID_COLS)
GRID_HEIGHT = Misc.calculate_grid_size(CELL_HEIGHT, CELL_SPACING,  GRID_COLS)
MARKER_RADIUS = CELL_WIDTH / 2.5

# WORLD GENERATOR
MAX_GENERATABLE_ROOMS_COUNT = 25 # For performace reosons
ROOM_CELL_SPACING = 1
ROOM_CELL_WIDTH = 16
ROOM_CELL_HEIGHT = ROOM_CELL_WIDTH
ROOM_PADDING = (2, 2) # Margin - Top Gap and left Gap
DEFAULT_ROOM_SIZE = 15 # Rows and Cols of the grid per room

# UI
# hud
PLAYER_HEALTH_BAR_WIDTH = SCREEN_WIDTH * (1/ 3)
PLAYER_HEALTH_BAR_HEIGHT = SCREEN_HEIGHT * 0.03
PLAYER_XP_BAR_HEIGHT = PLAYER_HEALTH_BAR_HEIGHT / 1.5
PLAYER_XP_BAR_WIDTH = PLAYER_HEALTH_BAR_WIDTH * 0.9
PLAYER_NAME_AND_LEVEL_LABEL_WIDTH = PLAYER_HEALTH_BAR_WIDTH
PLAYER_NAME_AND_LEVEL_LABEL_HEIGHT = PLAYER_HEALTH_BAR_HEIGHT * 1.5
ENEMY_INFO_SIZE = (SCREEN_WIDTH / 7, PLAYER_HEALTH_BAR_HEIGHT * 3)
PANEL_BORDER_SIZE = 0.002 * SCREEN_WIDTH
# Inventory
class INVENTORY:
    FULL_SIZE = (SCREEN_WIDTH / 2.25, SCREEN_HEIGHT / 2.25)

    TITLE_HEIGHT_IN_PERC = 0.1
    DISPLAY_SIZE = (FULL_SIZE[0], FULL_SIZE[1] * (1 - TITLE_HEIGHT_IN_PERC))

    ITEM_DESPLAY_WIDTH = DISPLAY_SIZE[0] * 0.6
    ITEM_DESPLAY_HEIGHT = DISPLAY_SIZE[0] * 0.075
    MAIN_RECT_CENTER = SCREEN_CENTER[0] + FULL_SIZE[0] / 3 , SCREEN_CENTER[1]
# Stats Display
class STATS_DISPLAY:
    FULL_SIZE = (SCREEN_WIDTH - INVENTORY.FULL_SIZE[0]) / 2, INVENTORY.FULL_SIZE[1]

# Misc
FPS_INFO_SIZE = (32, 32)
PLAYER_UI_SPACING = 1
INITIAL_ROOM_COUNT = 3

# COLORS
VISITED_MARKER_COLOR = (0, 0, 100)
CONNECTING_LINE_COLOR = (100, 100, 100)
ROOM_COLOR = (100, 0, 0)
DOOR_COLOR = (150, 150, 150)
BLANKS_COLOR = (15, 15, 15)
WALL_COLOR = (15, 15, 60)

class Color:
    RED = (200, 0, 0)
    DARK_GREY = (50, 50, 50)
    OFF_WHITE = (200, 200, 200)
    DARKER_GREY = (25, 25, 25)
    YELLOW = (75, 75, 0)
    LIGHT_YELLOW = (200, 200, 0)
    GREY = (125, 125, 125)
    BLACK = (0, 0, 0)
    LIGHT_DARK_GREY = (75, 75, 75)
    

# CAMERA
ZOOM = 2
CAMERA_SIZE = (SCREEN_WIDTH / ZOOM, SCREEN_HEIGHT / ZOOM)

class Controls:
    LEFT = pygame.K_LEFT, pygame.K_a
    RIGHT = pygame.K_RIGHT, pygame.K_d
    UP = pygame.K_UP, pygame.K_w
    DOWN = pygame.K_DOWN, pygame.K_s
    WASTE_MOVE = pygame.K_SPACE, pygame.K_q
    INVENTORY = pygame.K_e

    MOVEMENT = [key[i] for key in (LEFT, RIGHT, UP, DOWN, WASTE_MOVE) for i in range(2)]

class Font_Names:
    HUD = "Courier New"

# GAME CONSTANT
FPS = 60

PLAYER_BUFF_INCREASE_PERCENT = 0.1
PLAYER_SKILL_POINTS_PER_UPGRADE = 4

ENEMY_SPAWN_CHANCE = 50
BUSH_HAS_LOOT_CHANCE = 2
BUSH_SPAWN_CHANCE = 10
CHEST_SPAWN_CHANCE = 5

DESCRIPTION_MAX_WRAP_LENGHT = 20
VERSION = 0.8